//! rmcp stdio server bootstrap. Wires policy → SSH tunnel → MySQL adapter
//! → Anonymizer → AuditLog → Scanner → optional log adapter into a
//! `ToolContext`, then exposes the eight spec-defined MCP tools over a
//! stdio transport using `rmcp`.
//!
//! Handlers here are thin shims: they delegate to `ToolContext` methods
//! (which already do policy enforcement, anonymization, audit logging,
//! and error sanitization) and translate `Ok/Err` into rmcp's
//! `CallToolResult` shape.

use std::future::Future;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use rmcp::handler::server::router::tool::ToolRouter;
use rmcp::handler::server::tool::Parameters;
use rmcp::model::{CallToolResult, Content, ErrorData};
use rmcp::transport::stdio;
use rmcp::{tool, tool_handler, tool_router, ServerHandler, ServiceExt};
use serde::Serialize;

use crate::adapter::laravel_log::LaravelLogAdapter;
use crate::adapter::mysql::MysqlAdapter;
use crate::adapter::ssh_tunnel::{SshTunnel, TunnelSpec};
use crate::adapter::LogAdapter;
use crate::anon::Anonymizer;
use crate::audit::{self, AuditLog};
use crate::mcp::errors::ErrorSanitizer;
use crate::mcp::tools::{
    CountArgs, DistinctArgs, ExplainArgs, LogsContextArgs, LogsSearchArgs, LogsTailArgs,
    SampleArgs, SchemaArgs, ToolContext, ToolError,
};
use crate::policy::parser::{self, Policy};
use crate::scanner::Scanner;

#[derive(Debug, thiserror::Error)]
pub enum ServerError {
    #[error("policy: {0}")]
    Policy(#[from] crate::policy::parser::PolicyError),
    #[error("ssh tunnel: {0}")]
    Tunnel(#[from] crate::adapter::ssh_tunnel::TunnelError),
    #[error("mysql adapter: {0}")]
    Adapter(#[from] crate::adapter::AdapterError),
    #[error("audit: {0}")]
    Audit(#[from] crate::audit::AuditError),
    #[error("scanner: {0}")]
    Scanner(#[from] crate::scanner::ScannerError),
    #[error("missing env var `{0}` for connection password")]
    MissingPasswordEnv(String),
    #[error("rmcp service: {0}")]
    Rmcp(String),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// rmcp server handle. Holds the shared `ToolContext` plus the tool
/// router generated by the `#[tool_router]` macro. The SSH tunnel is
/// kept alive separately in `run` for its `Drop` side effect.
#[derive(Clone)]
pub struct GazeServer {
    ctx: Arc<ToolContext>,
    tool_router: ToolRouter<Self>,
}

#[tool_router(router = tool_router)]
impl GazeServer {
    pub fn new(ctx: Arc<ToolContext>) -> Self {
        Self {
            ctx,
            tool_router: Self::tool_router(),
        }
    }

    #[tool(name = "db.schema", description = "Return the schema of an allowed table.")]
    pub async fn db_schema(
        &self,
        Parameters(args): Parameters<SchemaArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.db_schema(args).await)
    }

    #[tool(name = "db.sample", description = "Sample anonymized rows from an allowed table.")]
    pub async fn db_sample(
        &self,
        Parameters(args): Parameters<SampleArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.db_sample(args).await)
    }

    #[tool(name = "db.count", description = "Count rows in an allowed table, optionally filtered.")]
    pub async fn db_count(
        &self,
        Parameters(args): Parameters<CountArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.db_count(args).await)
    }

    #[tool(name = "db.distinct", description = "List distinct values of an allowed column.")]
    pub async fn db_distinct(
        &self,
        Parameters(args): Parameters<DistinctArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.db_distinct(args).await)
    }

    #[tool(name = "db.explain", description = "Return the query plan for a filtered sample.")]
    pub async fn db_explain(
        &self,
        Parameters(args): Parameters<ExplainArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.db_explain(args).await)
    }

    #[tool(name = "logs.search", description = "Search the configured Laravel log for a pattern.")]
    pub async fn logs_search(
        &self,
        Parameters(args): Parameters<LogsSearchArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.logs_search(args).await)
    }

    #[tool(name = "logs.tail", description = "Return the last N lines of the configured Laravel log.")]
    pub async fn logs_tail(
        &self,
        Parameters(args): Parameters<LogsTailArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.logs_tail(args).await)
    }

    #[tool(name = "logs.context", description = "Return log lines for a given request id.")]
    pub async fn logs_context(
        &self,
        Parameters(args): Parameters<LogsContextArgs>,
    ) -> Result<CallToolResult, ErrorData> {
        to_result(self.ctx.logs_context(args).await)
    }
}

#[tool_handler(router = self.tool_router)]
impl ServerHandler for GazeServer {}

/// Serialize a `ToolContext` result into a JSON text content. On
/// `ToolError`, return an rmcp internal error whose message is the
/// already-sanitized `Display` form of the error (the `ToolContext`
/// methods pass adapter errors through the sanitizer before they get
/// here).
fn to_result<T: Serialize>(result: Result<T, ToolError>) -> Result<CallToolResult, ErrorData> {
    match result {
        Ok(value) => {
            let json = serde_json::to_string(&value)
                .map_err(|e| ErrorData::internal_error(e.to_string(), None))?;
            Ok(CallToolResult::success(vec![Content::text(json)]))
        }
        Err(err) => Err(ErrorData::internal_error(err.to_string(), None)),
    }
}

/// Entry point for `gaze serve`. Loads policy, opens SSH tunnel + MySQL
/// pool, builds the `ToolContext`, then hands off to the rmcp stdio
/// transport. Blocks until the MCP peer disconnects or `waiting()`
/// returns an error.
pub async fn run(policy_path: &Path, global_audit: bool) -> Result<(), ServerError> {
    // 1. Policy.
    let policy: Policy = parser::load_from_file(policy_path)?;
    let conn = policy
        .connection
        .get("production")
        .expect("validated: exactly one production connection");
    let password = std::env::var(&conn.password_env)
        .map_err(|_| ServerError::MissingPasswordEnv(conn.password_env.clone()))?;

    // 2. SSH tunnel — kept alive by the `_tunnel` binding; `Drop` tears
    // it down when `run` returns.
    let _tunnel = SshTunnel::open(&TunnelSpec {
        ssh_host: conn.ssh_host.clone(),
        local_port: conn.local_port,
        remote_host: conn.remote_host.clone(),
        remote_port: conn.remote_port,
    })?;

    // 3. MySQL through the tunnel.
    let url = format!(
        "mysql://{}:{}@127.0.0.1:{}/{}",
        conn.user, password, conn.local_port, conn.database,
    );
    let adapter = MysqlAdapter::connect(&url).await?;

    // 4. Anonymizer from classifier built from the policy.
    let classifier = parser::build_classifier(&policy);
    let anonymizer = Arc::new(Anonymizer::new(classifier));

    // 5. Audit log at the default path (project-local or global).
    let audit_path: PathBuf = audit::default_path(global_audit);
    let audit_log = Arc::new(AuditLog::open(&audit_path)?);

    // 6. Scanner compiled from strip patterns (empty slice if no logs).
    let strip_patterns: &[String] = policy
        .policy
        .logs
        .as_ref()
        .map(|l| &l.strip_patterns[..])
        .unwrap_or(&[]);
    let scanner = Scanner::compile(strip_patterns)?;

    // 7. Optional Laravel log adapter.
    let log_adapter: Option<Arc<dyn LogAdapter>> = policy
        .policy
        .logs
        .as_ref()
        .map(|l| Arc::new(LaravelLogAdapter::new(PathBuf::from(&l.path))) as Arc<dyn LogAdapter>);

    // 8. ToolContext bundles everything the handlers touch.
    let ctx = Arc::new(ToolContext {
        policy,
        adapter: Arc::new(adapter),
        anonymizer,
        audit: audit_log,
        sanitizer: ErrorSanitizer::default(),
        log_adapter,
        scanner,
    });

    // 9. Hand off to rmcp stdio transport.
    let server = GazeServer::new(ctx);
    let running = server
        .serve(stdio())
        .await
        .map_err(|e| ServerError::Rmcp(e.to_string()))?;
    running
        .waiting()
        .await
        .map_err(|e| ServerError::Rmcp(e.to_string()))?;

    Ok(())
}
