#!/usr/bin/env python3
"""Measure adopter-facing latency of the `gaze setup` policy on a quiet host.

Three measurements over the same stratified benchmark documents (seed 20260710;
the first sampled document is the warm-up and is never scored):

  pipeline      warm per-document `clean_ms` from the benchmark runner
                (`clean_for_bench`, the production pipeline) for the exact
                `gaze setup` policy without and with Nym, and for rules plus NER
                (`pass2-ner`) on this build and on a checkout at tag v0.14.0, so
                a code slowdown is separable from the setup policy's extra packs
                and locales. Also the cold first document and peak RSS.
  cli           one `gaze clean --policy` process per document against one
                `gaze daemon --policy` process with one JSONL request per
                document (the first request is cold), without and with Nym.
                Wall clock includes process start and model load for one-shot.
  conversation  one `gaze daemon` session, 10 turns; turn k re-sends turns
                1..k joined, as an agent loop does.
  proxy         one `gaze proxy serve --policy` process in front of a local
                echo upstream (no network, no provider time): one OpenAI chat
                request per document, wall clock per request. The upstream
                returns the forwarded text, so every accepted response must
                restore to the document exactly; a refusal (422) is counted,
                anything else fails the run.

The policies are generated by the `gaze` binary under test with
`gaze setup --non-interactive --policy-out <tmp> --force` (and
`--safety-net none` for the no-Nym policy), never hand-written: a hand-written
`[session] scope = "ephemeral"` policy makes one-shot `gaze clean` fail.

Timing is only a claim on a quiet host: at the start the 1-minute load average
must be below 2 and no foreign cargo, rustc, benchmark or OPF process may run;
at the end no foreign process may have appeared (the measured workload's own
load is expected). Both probes are recorded either way, and a run that fails
the gate says `timing invalid`. `--smoke` measures 3 documents, skips the gate
and is never a timing claim. Document text stays in memory.

Usage (from the repository root; needs `gaze setup` models and the pinned
dataset under target/bench-data/dataiku-en-de/):

    uv run --project scripts/bench python scripts/bench/cli-latency.py \\
        --baseline-root <checkout at the previous release> \\
        --baseline-version v0.15.0 --out latency.json
"""

from __future__ import annotations

import argparse
import contextlib
import hashlib
import importlib.util
import json
import math
import os
import re
import signal
import socket
import statistics
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import dataiku_en_de_gaze_bench as dataiku  # noqa: E402
import gaze_bench_score as score  # noqa: E402

_SPEC = importlib.util.spec_from_file_location("nym_warm_latency", HERE / "nym-warm-latency.py")
assert _SPEC is not None and _SPEC.loader is not None
nym_latency = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(nym_latency)

SEED = 20260710
DOCUMENTS = 30
SMOKE_DOCUMENTS = 3
CONVERSATION_TURNS = 10
QUIET_LOAD_1M = 2.0
# Released tags a baseline checkout may sit on; the rules+NER cell is measured on both builds.
BASELINE_COMMITS = {
    "v0.14.0": "616e8a10b957961f9f7dcb745610afa978783c3a",
    "v0.15.0": "5127788b089f0f6f4e3b8bcf176503953744be01",
}
PROXY_READY_TIMEOUT_S = 120.0
FOREIGN = re.compile(
    r"cargo (build|test|run|clippy)|rustc |clean_for_bench|run_no_opf_benchmark|"
    r"privacy-filter/venv/bin/opf|opf_daemon"
)


def summary(samples: list[float]) -> dict[str, float | int] | None:
    """p50, nearest-rank p95, max and mean in milliseconds; None without samples."""
    if not samples:
        return None
    ordered = sorted(samples)
    return {
        "n": len(ordered),
        "p50_ms": round(statistics.median(ordered), 2),
        "p95_ms": round(ordered[max(0, math.ceil(0.95 * len(ordered)) - 1)], 2),
        "max_ms": round(ordered[-1], 2),
        "mean_ms": round(statistics.mean(ordered), 2),
    }


def conversation_turns(texts: list[str], turns: int = CONVERSATION_TURNS) -> list[str]:
    """Turn k is turns 1..k joined, so every request re-sends the conversation so far."""
    return ["\n\n".join(texts[: k + 1]) for k in range(min(turns, len(texts)))]


def process_table() -> list[tuple[int, int, str]]:
    rows = subprocess.run(["ps", "axo", "pid=,ppid=,command="], capture_output=True, text=True, check=True)
    table = []
    for line in rows.stdout.splitlines():
        parts = line.split(None, 2)
        if len(parts) == 3 and parts[0].isdigit() and parts[1].isdigit():
            table.append((int(parts[0]), int(parts[1]), parts[2]))
    return table


def own_tree(table: list[tuple[int, int, str]], pid: int) -> set[int]:
    """`pid`, its ancestors (the launcher carries this script's arguments) and its
    descendants (the workload itself); none of them is foreign."""
    parent = {child: ppid for child, ppid, _ in table}
    ancestors, cursor = set(), pid
    while cursor and cursor not in ancestors:
        ancestors.add(cursor)
        cursor = parent.get(cursor, 0)
    # Descendants of `pid` only: every process descends from an ancestor such as pid 1.
    descendants, grew = {pid}, True
    while grew:
        grew = False
        for child, ppid, _ in table:
            if ppid in descendants and child not in descendants:
                descendants.add(child)
                grew = True
    return ancestors | descendants


def foreign_processes(table: list[tuple[int, int, str]], pid: int) -> list[str]:
    mine = own_tree(table, pid)
    return [f"{child} {command[:160]}" for child, _, command in table if child not in mine and FOREIGN.search(command)]


def host_probe(label: str) -> dict[str, object]:
    load = os.getloadavg()
    foreign = foreign_processes(process_table(), os.getpid())
    return {
        "label": label,
        "load_1m": round(load[0], 2),
        "load_5m": round(load[1], 2),
        "load_15m": round(load[2], 2),
        "foreign_processes": foreign,
        "quiet": load[0] < QUIET_LOAD_1M and not foreign,
    }


def verdict(before: dict[str, object], after: dict[str, object], smoke: bool) -> str:
    if smoke:
        return "smoke run, not a timing claim"
    if before["quiet"] and not after["foreign_processes"]:
        return "valid"
    return "timing invalid: host was not quiet for the whole window"


def max_rss_bytes(ru_maxrss: int) -> int:
    """`ru_maxrss` is bytes on macOS and KiB on Linux."""
    return ru_maxrss if sys.platform == "darwin" else ru_maxrss * 1024


def mib(value: int) -> float:
    return round(value / 2**20, 1)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


class Child:
    """A long-lived JSONL child whose peak RSS is read from its own rusage at exit."""

    def __init__(self, argv: list[str], env: dict[str, str]) -> None:
        self.process = subprocess.Popen(
            argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True, encoding="utf-8", env=env,
        )
        self.stderr: list[str] = []
        self._drain = threading.Thread(target=lambda: self.stderr.extend(self.process.stderr), daemon=True)
        self._drain.start()

    def request(self, payload: dict[str, object]) -> tuple[float, dict[str, object]]:
        assert self.process.stdin is not None and self.process.stdout is not None
        started = time.perf_counter()
        self.process.stdin.write(json.dumps(payload) + "\n")
        self.process.stdin.flush()
        line = self.process.stdout.readline()
        elapsed = (time.perf_counter() - started) * 1000.0
        if not line:
            raise RuntimeError(f"child exited (code {self.process.poll()}): {''.join(self.stderr)[-2000:]}")
        return elapsed, json.loads(line)

    def close(self) -> int:
        """Close stdin, reap the child and return its peak RSS in bytes."""
        assert self.process.stdin is not None
        self.process.stdin.close()
        _, status, usage = os.wait4(self.process.pid, 0)
        self.process.returncode = os.waitstatus_to_exitcode(status)
        self._drain.join(timeout=5)
        for stream in (self.process.stdout, self.process.stderr):
            stream.close()
        if self.process.returncode != 0:
            raise RuntimeError(f"child exited {self.process.returncode}: {''.join(self.stderr)[-2000:]}")
        return max_rss_bytes(usage.ru_maxrss)


def run_once(argv: list[str], text: str, env: dict[str, str]) -> tuple[float, int, str, int]:
    """One process to exit: wall clock ms, exit code, stderr tail, peak RSS bytes."""
    started = time.perf_counter()
    process = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
    captured: dict[str, bytes] = {}
    readers = [
        threading.Thread(target=lambda name=name, stream=stream: captured.__setitem__(name, stream.read()))
        for name, stream in (("stdout", process.stdout), ("stderr", process.stderr))
    ]
    for reader in readers:
        reader.start()
    assert process.stdin is not None
    process.stdin.write(text.encode("utf-8"))
    process.stdin.close()
    _, status, usage = os.wait4(process.pid, 0)
    elapsed = (time.perf_counter() - started) * 1000.0
    process.returncode = os.waitstatus_to_exitcode(status)
    for reader in readers:
        reader.join()
    for stream in (process.stdout, process.stderr):
        stream.close()
    stderr = captured.get("stderr", b"").decode("utf-8", "replace")[-2000:]
    return elapsed, process.returncode, stderr, max_rss_bytes(usage.ru_maxrss)


def generate_policy(gaze: Path, out: Path, nym: bool, env: dict[str, str]) -> Path:
    command = [str(gaze), "setup", "--non-interactive", "--policy-out", str(out), "--force"]
    if not nym:
        command += ["--safety-net", "none"]
    subprocess.run(command, check=True, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    return out


def pipeline_arm(binary: Path, config: str, documents: list[score.Document], env: dict[str, str]) -> dict[str, object]:
    """Warm `clean_ms` after one cold document; any pipeline error fails the run."""
    child = Child([str(binary), "--config", config], env)
    clean_ms, cold_ms = [], None
    for index, document in enumerate(documents):
        elapsed, response = child.request(
            {"fixture_id": document.uid, "locale_chain": list(document.locale_chain), "text": document.text}
        )
        if "pipeline_error_stage" in response:
            raise RuntimeError(f"{config}: {document.uid} failed at {response['pipeline_error_stage']}")
        if index == 0:
            cold_ms = round(elapsed, 1)
        else:
            clean_ms.append(float(response["timing"]["clean_ms"]))
    peak = child.close()
    return {"cold_first_document_ms": cold_ms, "warm_clean": summary(clean_ms), "peak_rss_mib": mib(peak)}


def oneshot_arm(gaze: Path, policy: Path, texts: list[str], env: dict[str, str]) -> dict[str, object]:
    samples, peak = [], 0
    for text in texts:
        elapsed, code, stderr, rss = run_once([str(gaze), "clean", "--policy", str(policy)], text, env)
        if code != 0:
            raise RuntimeError(f"gaze clean exited {code}: {stderr}")
        samples.append(elapsed)
        peak = max(peak, rss)
    return {"per_document": summary(samples), "peak_rss_mib": mib(peak)}


def daemon_arm(gaze: Path, policy: Path, requests: list[tuple[str, str]], env: dict[str, str]) -> dict[str, object]:
    """The first request is cold (model load happens on it); the rest are warm."""
    child = Child([str(gaze), "daemon", "--policy", str(policy)], env)
    samples, cold_ms = [], None
    for index, (session, text) in enumerate(requests):
        elapsed, response = child.request({"session_id": session, "text": text})
        if "error" in response:
            raise RuntimeError(f"gaze daemon: {response['error']}: {response.get('detail')}")
        if index == 0:
            cold_ms = round(elapsed, 1)
        else:
            samples.append(elapsed)
    peak = child.close()
    return {"first_request_cold_ms": cold_ms, "warm": summary(samples), "peak_rss_mib": mib(peak)}


def conversation_arm(gaze: Path, policy: Path, turns: list[str], env: dict[str, str]) -> dict[str, object]:
    child = Child([str(gaze), "daemon", "--policy", str(policy)], env)
    rows = []
    for turn, text in enumerate(turns, start=1):
        elapsed, response = child.request({"session_id": "conversation-1", "text": text})
        if "error" in response:
            raise RuntimeError(f"gaze daemon turn {turn}: {response['error']}: {response.get('detail')}")
        rows.append({"turn": turn, "bytes": len(text.encode("utf-8")), "ms": round(elapsed, 2)})
    peak = child.close()
    return {"turns": rows, "turn_1_is_cold": True, "peak_rss_mib": mib(peak)}


class EchoUpstream(BaseHTTPRequestHandler):
    """An OpenAI chat endpoint that answers with the last message it was sent."""

    def do_POST(self) -> None:  # noqa: N802 (http.server naming)
        body = json.loads(self.rfile.read(int(self.headers["Content-Length"])))
        payload = json.dumps({
            "id": "chatcmpl-latency",
            "object": "chat.completion",
            "model": body.get("model"),
            "choices": [{"index": 0, "finish_reason": "stop",
                         "message": {"role": "assistant", "content": body["messages"][-1]["content"]}}],
        }).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, *_: object) -> None:
        pass


def free_port() -> int:
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def chat_request(base: str, text: str) -> tuple[float, int, str | None]:
    """One chat request: wall clock ms, HTTP status, and the restored reply text (200 only)."""
    request = urllib.request.Request(
        f"{base}/v1/chat/completions",
        data=json.dumps({"model": "latency", "messages": [{"role": "user", "content": text}]}).encode("utf-8"),
        headers={"Content-Type": "application/json", "Authorization": "Bearer sk-latency-dummy"},
    )
    started = time.perf_counter()
    try:
        with urllib.request.urlopen(request, timeout=300) as response:
            status, body = response.status, response.read()
    except urllib.error.HTTPError as error:
        status, body = error.code, error.read()
    elapsed = (time.perf_counter() - started) * 1000.0
    reply = json.loads(body)["choices"][0]["message"]["content"] if status == 200 else None
    return elapsed, status, reply


def proxy_arm(gaze: Path, policy: Path, texts: list[str], env: dict[str, str]) -> dict[str, object]:
    """`gaze proxy serve` in front of an echo upstream. The first request is cold."""
    upstream = ThreadingHTTPServer(("127.0.0.1", 0), EchoUpstream)
    threading.Thread(target=upstream.serve_forever, daemon=True).start()
    base = f"http://127.0.0.1:{free_port()}"
    argv = [str(gaze), "proxy", "serve", "--bind", base.removeprefix("http://"),
            "--upstream-openai", f"http://127.0.0.1:{upstream.server_port}", "--policy", str(policy)]
    started = time.perf_counter()
    process = subprocess.Popen(argv, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, env=env)
    stderr: list[bytes] = []
    drain = threading.Thread(target=lambda: stderr.extend(process.stderr), daemon=True)
    drain.start()
    try:
        while True:
            if process.poll() is not None:
                raise RuntimeError(f"gaze proxy exited {process.returncode}: {b''.join(stderr)[-2000:]!r}")
            if time.perf_counter() - started > PROXY_READY_TIMEOUT_S:
                raise RuntimeError("gaze proxy did not become ready")
            with contextlib.suppress(OSError):
                with urllib.request.urlopen(f"{base}/_gaze_proxy/healthz", timeout=1):
                    break
            time.sleep(0.05)
        ready_ms = (time.perf_counter() - started) * 1000.0
        samples, statuses, cold_ms, restored = [], {}, None, 0
        for index, text in enumerate([texts[0], *texts]):
            elapsed, status, reply = chat_request(base, text)
            if status not in (200, 422):
                raise RuntimeError(f"gaze proxy answered {status}")
            if index == 0:
                cold_ms = round(elapsed, 1)
                continue
            samples.append(elapsed)
            statuses[str(status)] = statuses.get(str(status), 0) + 1
            if status == 200:
                if reply != text:
                    raise RuntimeError("gaze proxy reply did not restore to the sent document")
                restored += 1
    finally:
        process.send_signal(signal.SIGTERM)
        _, _, usage = os.wait4(process.pid, 0)
        drain.join(timeout=5)
        process.stderr.close()
        upstream.shutdown()
        upstream.server_close()
    return {
        "ready_ms": round(ready_ms, 1),
        "first_request_cold_ms": cold_ms,
        "warm": summary(samples),
        "status_counts": statuses,
        "restored_exact": restored,
        "peak_rss_mib": mib(max_rss_bytes(usage.ru_maxrss)),
    }


def build(root: Path, target_dir: Path | None, *args: str) -> None:
    env = dict(os.environ)
    if target_dir is not None:
        env["CARGO_TARGET_DIR"] = str(target_dir)
    subprocess.run(["cargo", "build", "--release", "-q", *args], cwd=root, env=env, check=True)


def baseline_binary(args: argparse.Namespace) -> Path | None:
    """clean_for_bench from a checkout at the baseline tag, built in its own target dir."""
    if args.baseline_binary is not None:
        return args.baseline_binary
    if args.baseline_root is None:
        return None
    root = args.baseline_root.resolve()
    head = subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"], capture_output=True, text=True, check=True)
    expected = BASELINE_COMMITS[args.baseline_version]
    if head.stdout.strip() != expected:
        raise SystemExit(f"--baseline-root is at {head.stdout.strip()}, not {args.baseline_version} ({expected})")
    if not args.skip_build:
        build(root, root / "target", "-p", "gaze-recognizers", "--example", "clean_for_bench")
    return root / "target/release/examples/clean_for_bench"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--repo-root", type=Path, default=Path.cwd())
    parser.add_argument("--dataset", type=Path, default=Path("target/bench-data/dataiku-en-de/test.parquet"))
    parser.add_argument("--documents", type=int, default=DOCUMENTS)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--baseline-version", choices=sorted(BASELINE_COMMITS), default="v0.14.0",
                        help="released tag the baseline checkout or binary is built from")
    parser.add_argument("--baseline-root", type=Path, help="checkout at --baseline-version; built in <root>/target")
    parser.add_argument("--baseline-binary", type=Path,
                        help="prebuilt clean_for_bench of --baseline-version (skips the build)")
    parser.add_argument("--ner-model-dir", type=Path,
                        default=nym_latency.default_model_dir("GAZE_NER_MODEL_DIR", "davlan-mbert-ner-hrl"))
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--smoke", action="store_true",
                        help=f"{SMOKE_DOCUMENTS} documents, no quiet-host gate, never a timing claim")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    root = args.repo_root.resolve()
    documents_wanted = SMOKE_DOCUMENTS if args.smoke else args.documents

    before = host_probe("before")
    if not before["quiet"] and not args.smoke:
        args.out.write_text(json.dumps({"verdict": "timing invalid: host not quiet at start; nothing measured",
                                        "host_before": before}, indent=2) + "\n", encoding="utf-8")
        print("timing invalid: host not quiet at start", file=sys.stderr)
        return 1

    target_dir = Path(os.environ.get("CARGO_TARGET_DIR", str(root / "target")))
    if not args.skip_build:
        build(root, None, "-p", "gaze-cli")
    bench = dataiku.build_binary(root, ("policy-file",), release=True) if not args.skip_build \
        else target_dir / "release/examples/clean_for_bench"
    gaze = target_dir / "release/gaze"
    baseline = baseline_binary(args)

    dataset = args.dataset if args.dataset.is_absolute() else root / args.dataset
    positive, _ = dataiku.load_documents(dataset)
    documents, _ = score.stratified_sample(positive, documents_wanted + 1, SEED)
    texts = [document.text for document in documents[1:]]
    turns = conversation_turns(texts)

    info = nym_latency.host_info(root)
    result: dict[str, object] = {
        "hardware": nym_latency.hardware_line(info),
        "host": info,
        "git_head": subprocess.run(["git", "-C", str(root), "rev-parse", "HEAD"],
                                   capture_output=True, text=True, check=True).stdout.strip(),
        "seed": SEED,
        "documents": len(texts),
        "smoke": args.smoke,
        "host_before": before,
        "binaries": {"gaze": sha256_file(gaze), "clean_for_bench": sha256_file(bench)},
    }
    with tempfile.TemporaryDirectory(prefix="gaze-cli-latency-") as scratch:
        env = dict(os.environ)
        policies = {
            "setup": generate_policy(gaze, Path(scratch) / "setup.toml", False, env),
            "setup_nym": generate_policy(gaze, Path(scratch) / "setup-nym.toml", True, env),
        }
        result["policy_sha256"] = {name: sha256_file(path) for name, path in policies.items()}

        pipeline: dict[str, object] = {}
        for name, path in policies.items():
            pipeline[name] = pipeline_arm(bench, "policy-file", documents, {**env, "GAZE_BENCH_POLICY": str(path)})
        # The same rules+NER cell on both builds separates a code slowdown from the
        # extra packs and locales the setup policy loads.
        rules_ner_env = {**env, "GAZE_NER_MODEL_DIR": str(args.ner_model_dir), "GAZE_NER_THRESHOLD": "0.3"}
        pipeline["rules_ner"] = pipeline_arm(bench, "pass2-ner", documents, rules_ner_env)
        if baseline is not None:
            key = args.baseline_version.replace(".", "_")
            result["baseline_version"] = args.baseline_version
            result["binaries"][f"clean_for_bench_{key}"] = sha256_file(baseline)
            pipeline[f"{key}_rules_ner"] = pipeline_arm(baseline, "pass2-ner", documents, rules_ner_env)
        result["pipeline"] = pipeline

        cli: dict[str, object] = {}
        conversation: dict[str, object] = {}
        for name, path in policies.items():
            cli[f"oneshot_{name}"] = oneshot_arm(gaze, path, texts, env)
            cli[f"daemon_{name}"] = daemon_arm(
                gaze, path, [(f"doc-{index}", text) for index, text in enumerate([texts[0], *texts])], env
            )
            conversation[name] = conversation_arm(gaze, path, turns, env)
        result["cli"] = cli
        result["conversation"] = conversation
        result["proxy"] = {name: proxy_arm(gaze, path, texts, env) for name, path in policies.items()}

    after = host_probe("after")
    result["host_after"] = after
    result["verdict_rule"] = (f"start: load_1m < {QUIET_LOAD_1M} and no foreign process; "
                              "end: no foreign process (the workload's own load is expected)")
    result["verdict"] = verdict(before, after, args.smoke)
    args.out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"verdict": result["verdict"], "out": str(args.out)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
